In [ ]:
#Business requirement

In [85]:
#data collection/Preprocessing
import numpy as np
import pandas as pd

In [86]:
from sklearn.model_selection import train_test_split

In [87]:
heart = pd.read_csv('clevelanda.csv')

In [88]:
heart.head()

,age,gender,cp,trestbps,chol,fps,restecg,thalach,exang,oldpeak,slope,ca,thal,class
0,63,1,1,145,233,1,2,150,0,2.3,3,0,6,0
1,67,1,4,160,286,0,2,108,1,1.5,2,3,3,2
2,67,1,4,120,229,0,2,129,1,2.6,2,2,7,1
3,37,1,3,130,250,0,0,187,0,3.5,3,0,3,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0,3,0

In [89]:
#data cleaning
heart.info() # 11& 12 are objects

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   gender    303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fps       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    object
 12  thal      303 non-null    object
 13  class     303 non-null    int64
dtypes: float64(1), int64(11), object(2)
memory usage: 33.3+ KB

In [90]:
heart = heart.replace('?', np.nan)

In [91]:
heart = heart.dropna()

In [92]:
#split data into input and output
# since there are objects/ special characters in the data, convert into numerical values
heart['class'].value_counts() # 0 = no heart disease, 1 = heart disease 
#denotes classified

class
0    160
1     54
2     35
3     35
4     13
Name: count, dtype: int64

In [93]:
x = heart.iloc[:, 0:13]

In [94]:
x.head()

,age,gender,cp,trestbps,chol,fps,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,1,145,233,1,2,150,0,2.3,3,0,6
1,67,1,4,160,286,0,2,108,1,1.5,2,3,3
2,67,1,4,120,229,0,2,129,1,2.6,2,2,7
3,37,1,3,130,250,0,0,187,0,3.5,3,0,3
4,41,0,2,130,204,0,2,172,0,1.4,1,0,3

In [95]:
y = heart.iloc[:, 13:]
y.head()

   class
0      0
1      2
2      1
3      0
4      0

In [96]:
#split data into train and test
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [97]:
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression

In [98]:
sgd_classifier = SGDClassifier()

In [99]:
sgd_clf.fit(X_train,y_train)

c:\Users\A\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SGDClassifier()

In [100]:
sgd_clf.coef_ #13*5 # 13 features and 5 classes (0,1,2,3,4)

array([[-3.64455364e+02, -5.81490581e+02, -1.18038493e+03,
        -9.33660934e+02, -3.82882883e+02,  1.23873874e+02,
        -3.57289107e+02,  1.38820639e+03, -5.83538084e+02,
        -1.21304259e+03, -3.70597871e+02, -1.49160524e+03,
        -3.05384930e+03],
       [-2.10240760e+01,  2.59749067e+02,  6.30722279e+01,
         8.81654798e+00,  1.62767040e+02, -2.11597152e+02,
        -2.71278399e+00, -1.48524924e+02,  1.79721940e+02,
        -1.57409291e+02, -6.37504239e+01,  3.66225839e+01,
         6.93794507e+02],
       [ 6.65465225e+02,  1.28153785e+02,  5.17954879e+02,
        -4.67227339e+00,  9.21105326e+01,  4.67227339e+00,
        -5.53998131e+01, -4.47203311e+02,  2.00240288e+02,
         6.64530770e+02,  9.27780003e+01,  4.93258577e+02,
         9.91189427e+02],
       [-8.38867529e+01,  1.89910288e+02,  4.12443202e+02,
         9.11103344e+02,  2.91273448e+01,  1.17674473e+02,
         2.95933823e+02, -1.32005126e+03,  2.55155540e+02,
         5.34195503e+02,  2.16707445e+02,  6.30315740e+02,
         1.43889083e+03],
       [ 6.20994990e+02,  1.98065944e+01,  1.87580100e+02,
         3.63509262e+02, -1.28160317e+02, -4.66037516e+01,
         2.44669696e+02, -1.13363626e+03, -1.74764069e+01,
         3.08050798e+02,  8.73820343e+01,  3.55353606e+02,
         2.03891413e+02]])

In [101]:
# ML/DL Testing
y_pred = sgd_clf.predict(X_test)

In [102]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [103]:
y_test.head()

     class
169      0
214      1
63       0
155      1
5        0

In [104]:
#ML /DL Evaluation
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [105]:
accuracy_score(y_test,y_pred)

0.25

In [106]:
#train accuracy
y_train_pred = sgd_clf.predict(X_train)

In [107]:
accuracy_score(y_train,y_train_pred)

0.25316455696202533